/// Flutter icons Mea
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Mea
///      fonts:
///       - asset: fonts/Mea.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MeaIcons {
  MeaIcons._();

  static const _kFontFam = 'Mea';
  static const _kFontPkg = null;

  static const IconData door = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
